from geopy.geocoders import Nominatim
import time

def generate_delhi_locations_db():

    geolocator = Nominatim(user_agent="nuclear_fallout_app")

    places_to_find = [
        "Kashmere Gate, Delhi", "Malviya Nagar, Delhi", "Delhi Airport",
        "Red Fort, Delhi", "India Gate, New Delhi", "Hauz Khas, Delhi",
        "Connaught Place, New Delhi", "Karol Bagh, Delhi", "Lajpat Nagar, Delhi",
        "Dwarka, New Delhi", "Rajouri Garden, Delhi", "Chandni Chowk, Delhi",
        "Greater Kailash, New Delhi", "Rohini, Delhi", "Saket, New Delhi",
        "Nehru Place, Delhi", "Sarojini Nagar Market", "Kamla Nagar Market",
        "Defence Colony, Delhi", "Green Park, Delhi", "Okhla Industrial Area, Delhi",
        "Nizamuddin, Delhi", "Chanakyapuri, Delhi", "Lutyens' Delhi",
        "Akshardham Temple, Delhi", "Lotus Temple, Delhi", "Qutub Minar, Delhi",
        "National Museum, New Delhi", "Humayun's Tomb, Delhi", "Mehrauli, Delhi",
        "Jawaharlal Nehru University, New Delhi", "Delhi University"
    ]

    delhi_locations = {}

    print("Generating comprehensive Delhi location database...")
    for place in places_to_find:
        print(f"Fetching coordinates for: {place}...")
        try:

            time.sleep(1)
            location = geolocator.geocode(place, timeout=10)
            if location:
                delhi_locations[place.lower()] = (location.latitude, location.longitude)
                print(f"Found: {location.address}")
            else:
                print(f"Could not find coordinates for: {place}")
        except Exception as e:
            print(f"Error fetching {place}: {e}")

    output_file_path = "delhi_locations.py"
    with open(output_file_path, "w") as f:
        f.write("# This file was auto-generated by generate_comprehensive_locations.py\n")
        f.write("# Do not edit manually.\n\n")
        f.write("DELHI_LOCATIONS = {\n")
        for name, coords in delhi_locations.items():
            f.write(f"    '{name}': {coords},\n")
        f.write("}\n\n")

        f.write("def get_coordinates(place_name):\n")
        f.write("    \"\"\"Returns the coordinates for a given place name.\"\"\"\n")
        f.write("    return DELHI_LOCATIONS.get(place_name.lower())\n")

    print(f"\nSuccessfully generated {output_file_path} with {len(delhi_locations)} locations.")

if __name__ == "__main__":
    generate_delhi_locations_db()

